
// AUTOGENERATED from SMART OWL Ontology.  Do not edit.
(function(context) {
  if (!context.smart_parser) {
    context.smart_parser = {};
  }

  var type_definitions = {};
  context.smart_parser.type_definitions = type_definitions;


  type_definitions["<http://www.w3.org/2006/vcard/ns#Address>"] = { 
    name: "Address",
    uri: "<http://www.w3.org/2006/vcard/ns#Address>",
    is_statement: false,
    data_properties: [ 
      {
        name: "country-name", 
        uri: "<http://www.w3.org/2006/vcard/ns#country-name>",
        allow_list: false
      },
      {
        name: "extended-address", 
        uri: "<http://www.w3.org/2006/vcard/ns#extended-address>",
        allow_list: false
      },
      {
        name: "locality", 
        uri: "<http://www.w3.org/2006/vcard/ns#locality>",
        allow_list: false
      },
      {
        name: "postal-code", 
        uri: "<http://www.w3.org/2006/vcard/ns#postal-code>",
        allow_list: false
      },
      {
        name: "region", 
        uri: "<http://www.w3.org/2006/vcard/ns#region>",
        allow_list: false
      },
      {
        name: "street-address", 
        uri: "<http://www.w3.org/2006/vcard/ns#street-address>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Alert>"] = { 
    name: "Alert",
    uri: "<http://smartplatforms.org/terms#Alert>",
    is_statement: true,
    data_properties: [ 
      {
        name: "notes", 
        uri: "<http://smartplatforms.org/terms#notes>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "alertLevel", 
        uri: "<http://smartplatforms.org/terms#alertLevel>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      },
      {
        name: "belongsTo", 
        uri: "<http://smartplatforms.org/terms#belongsTo>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#MedicalRecord>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/AlertLevel>"] = { 
    name: "AlertLevel",
    uri: "<http://smartplatforms.org/terms/codes/AlertLevel>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Allergy>"] = { 
    name: "Allergy",
    uri: "<http://smartplatforms.org/terms#Allergy>",
    is_statement: true,
    data_properties: [  
    ],
    object_properties: [ 
      {
        name: "allergicReaction", 
        uri: "<http://smartplatforms.org/terms#allergicReaction>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      },
      {
        name: "belongsTo", 
        uri: "<http://smartplatforms.org/terms#belongsTo>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#MedicalRecord>"
      },
      {
        name: "category", 
        uri: "<http://smartplatforms.org/terms#category>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      },
      {
        name: "drugAllergen", 
        uri: "<http://smartplatforms.org/terms#drugAllergen>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      },
      {
        name: "drugClassAllergen", 
        uri: "<http://smartplatforms.org/terms#drugClassAllergen>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      },
      {
        name: "foodAllergen", 
        uri: "<http://smartplatforms.org/terms#foodAllergen>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      },
      {
        name: "severity", 
        uri: "<http://smartplatforms.org/terms#severity>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#AllergyExclusion>"] = { 
    name: "Allergy Exclusion",
    uri: "<http://smartplatforms.org/terms#AllergyExclusion>",
    is_statement: true,
    data_properties: [  
    ],
    object_properties: [ 
      {
        name: "allergyExclusionName", 
        uri: "<http://smartplatforms.org/terms#allergyExclusionName>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      },
      {
        name: "belongsTo", 
        uri: "<http://smartplatforms.org/terms#belongsTo>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#MedicalRecord>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/AllergyCategory>"] = { 
    name: "AllergyCategory",
    uri: "<http://smartplatforms.org/terms/codes/AllergyCategory>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/AllergyExclusion>"] = { 
    name: "AllergyExclusion",
    uri: "<http://smartplatforms.org/terms/codes/AllergyExclusion>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/AllergySeverity>"] = { 
    name: "AllergySeverity",
    uri: "<http://smartplatforms.org/terms/codes/AllergySeverity>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#AppManifest>"] = { 
    name: "App Manifest",
    uri: "<http://smartplatforms.org/terms#AppManifest>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Attribution>"] = { 
    name: "Attribution",
    uri: "<http://smartplatforms.org/terms#Attribution>",
    is_statement: false,
    data_properties: [ 
      {
        name: "endDate", 
        uri: "<http://smartplatforms.org/terms#endDate>",
        allow_list: false
      },
      {
        name: "startDate", 
        uri: "<http://smartplatforms.org/terms#startDate>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "participant", 
        uri: "<http://smartplatforms.org/terms#participant>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#Participant>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#BloodPressure>"] = { 
    name: "BloodPressure",
    uri: "<http://smartplatforms.org/terms#BloodPressure>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [ 
      {
        name: "bodyPosition", 
        uri: "<http://smartplatforms.org/terms#bodyPosition>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      },
      {
        name: "bodySite", 
        uri: "<http://smartplatforms.org/terms#bodySite>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      },
      {
        name: "diastolic", 
        uri: "<http://smartplatforms.org/terms#diastolic>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#VitalSign>"
      },
      {
        name: "method", 
        uri: "<http://smartplatforms.org/terms#method>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      },
      {
        name: "systolic", 
        uri: "<http://smartplatforms.org/terms#systolic>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#VitalSign>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/BloodPressureBodyPosition>"] = { 
    name: "BloodPressureBodyPosition",
    uri: "<http://smartplatforms.org/terms/codes/BloodPressureBodyPosition>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/BloodPressureBodySite>"] = { 
    name: "BloodPressureBodySite",
    uri: "<http://smartplatforms.org/terms/codes/BloodPressureBodySite>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/BloodPressureMethod>"] = { 
    name: "BloodPressureMethod",
    uri: "<http://smartplatforms.org/terms/codes/BloodPressureMethod>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Container>"] = { 
    name: "Capabilities",
    uri: "<http://smartplatforms.org/terms#Container>",
    is_statement: false,
    data_properties: [ 
      {
        name: "capability", 
        uri: "<http://smartplatforms.org/terms#capability>",
        allow_list: true
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://www.w3.org/2006/vcard/ns#Cell>"] = { 
    name: "Cell",
    uri: "<http://www.w3.org/2006/vcard/ns#Cell>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Code>"] = { 
    name: "Code",
    uri: "<http://smartplatforms.org/terms#Code>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#CodeProvenance>"] = { 
    name: "CodeProvenance",
    uri: "<http://smartplatforms.org/terms#CodeProvenance>",
    is_statement: false,
    data_properties: [ 
      {
        name: "sourceCode", 
        uri: "<http://smartplatforms.org/terms#sourceCode>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "translationFidelity", 
        uri: "<http://smartplatforms.org/terms#translationFidelity>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms/codes/TranslationFidelity>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#CodedValue>"] = { 
    name: "Coded Value",
    uri: "<http://smartplatforms.org/terms#CodedValue>",
    is_statement: false,
    data_properties: [ 
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "code", 
        uri: "<http://smartplatforms.org/terms#code>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#Code>"
      },
      {
        name: "provenance", 
        uri: "<http://smartplatforms.org/terms#provenance>",
        allow_list: true,
        target: "<http://smartplatforms.org/terms#CodeProvenance>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Component>"] = { 
    name: "Component",
    uri: "<http://smartplatforms.org/terms#Component>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#DataType>"] = { 
    name: "DataType",
    uri: "<http://smartplatforms.org/terms#DataType>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Demographics>"] = { 
    name: "Demographics",
    uri: "<http://smartplatforms.org/terms#Demographics>",
    is_statement: true,
    data_properties: [ 
      {
        name: "bday", 
        uri: "<http://www.w3.org/2006/vcard/ns#bday>",
        allow_list: false
      },
      {
        name: "email", 
        uri: "<http://www.w3.org/2006/vcard/ns#email>",
        allow_list: false
      },
      {
        name: "ethnicity", 
        uri: "<http://smartplatforms.org/terms#ethnicity>",
        allow_list: false
      },
      {
        name: "gender", 
        uri: "<http://xmlns.com/foaf/0.1/gender>",
        allow_list: false
      },
      {
        name: "preferredLanguage", 
        uri: "<http://smartplatforms.org/terms#preferredLanguage>",
        allow_list: false
      },
      {
        name: "race", 
        uri: "<http://smartplatforms.org/terms#race>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "adr", 
        uri: "<http://www.w3.org/2006/vcard/ns#adr>",
        allow_list: true,
        target: "<http://www.w3.org/2006/vcard/ns#Address>"
      },
      {
        name: "belongsTo", 
        uri: "<http://smartplatforms.org/terms#belongsTo>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#MedicalRecord>"
      },
      {
        name: "medicalRecordNumber", 
        uri: "<http://smartplatforms.org/terms#medicalRecordNumber>",
        allow_list: true,
        target: "<http://smartplatforms.org/terms#Code>"
      },
      {
        name: "n", 
        uri: "<http://www.w3.org/2006/vcard/ns#n>",
        allow_list: false,
        target: "<http://www.w3.org/2006/vcard/ns#Name>"
      },
      {
        name: "tel", 
        uri: "<http://www.w3.org/2006/vcard/ns#tel>",
        allow_list: true,
        target: "<http://www.w3.org/2006/vcard/ns#Tel>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Encounter>"] = { 
    name: "Encounter",
    uri: "<http://smartplatforms.org/terms#Encounter>",
    is_statement: true,
    data_properties: [ 
      {
        name: "endDate", 
        uri: "<http://smartplatforms.org/terms#endDate>",
        allow_list: false
      },
      {
        name: "startDate", 
        uri: "<http://smartplatforms.org/terms#startDate>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "belongsTo", 
        uri: "<http://smartplatforms.org/terms#belongsTo>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#MedicalRecord>"
      },
      {
        name: "encounterType", 
        uri: "<http://smartplatforms.org/terms#encounterType>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      },
      {
        name: "facility", 
        uri: "<http://smartplatforms.org/terms#facility>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#Organization>"
      },
      {
        name: "provider", 
        uri: "<http://smartplatforms.org/terms#provider>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#Provider>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/EncounterType>"] = { 
    name: "EncounterType",
    uri: "<http://smartplatforms.org/terms/codes/EncounterType>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Fulfillment>"] = { 
    name: "Fulfillment",
    uri: "<http://smartplatforms.org/terms#Fulfillment>",
    is_statement: true,
    data_properties: [ 
      {
        name: "date", 
        uri: "<http://purl.org/dc/terms/date>",
        allow_list: false
      },
      {
        name: "dispenseDaysSupply", 
        uri: "<http://smartplatforms.org/terms#dispenseDaysSupply>",
        allow_list: false
      },
      {
        name: "pbm", 
        uri: "<http://smartplatforms.org/terms#pbm>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "belongsTo", 
        uri: "<http://smartplatforms.org/terms#belongsTo>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#MedicalRecord>"
      },
      {
        name: "medication", 
        uri: "<http://smartplatforms.org/terms#medication>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#Medication>"
      },
      {
        name: "pharmacy", 
        uri: "<http://smartplatforms.org/terms#pharmacy>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#Pharmacy>"
      },
      {
        name: "provider", 
        uri: "<http://smartplatforms.org/terms#provider>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#Provider>"
      },
      {
        name: "quantityDispensed", 
        uri: "<http://smartplatforms.org/terms#quantityDispensed>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#ValueAndUnit>"
      } 
    ]
  };


  type_definitions["<http://www.w3.org/2006/vcard/ns#Home>"] = { 
    name: "Home",
    uri: "<http://www.w3.org/2006/vcard/ns#Home>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/LOINC>"] = { 
    name: "LOINC",
    uri: "<http://smartplatforms.org/terms/codes/LOINC>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#LabResult>"] = { 
    name: "Lab Result",
    uri: "<http://smartplatforms.org/terms#LabResult>",
    is_statement: true,
    data_properties: [ 
      {
        name: "accessionNumber", 
        uri: "<http://smartplatforms.org/terms#accessionNumber>",
        allow_list: false
      },
      {
        name: "notes", 
        uri: "<http://smartplatforms.org/terms#notes>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "abnormalInterpretation", 
        uri: "<http://smartplatforms.org/terms#abnormalInterpretation>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      },
      {
        name: "belongsTo", 
        uri: "<http://smartplatforms.org/terms#belongsTo>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#MedicalRecord>"
      },
      {
        name: "labName", 
        uri: "<http://smartplatforms.org/terms#labName>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      },
      {
        name: "labStatus", 
        uri: "<http://smartplatforms.org/terms#labStatus>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      },
      {
        name: "narrativeResult", 
        uri: "<http://smartplatforms.org/terms#narrativeResult>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#NarrativeResult>"
      },
      {
        name: "quantitativeResult", 
        uri: "<http://smartplatforms.org/terms#quantitativeResult>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#QuantitativeResult>"
      },
      {
        name: "specimenCollected", 
        uri: "<http://smartplatforms.org/terms#specimenCollected>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#Attribution>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/LabResultInterpretation>"] = { 
    name: "LabResultInterpretation",
    uri: "<http://smartplatforms.org/terms/codes/LabResultInterpretation>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#LabResultPanel>"] = { 
    name: "LabResultPanel",
    uri: "<http://smartplatforms.org/terms#LabResultPanel>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [ 
      {
        name: "labName", 
        uri: "<http://smartplatforms.org/terms#labName>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      },
      {
        name: "labResult", 
        uri: "<http://smartplatforms.org/terms#labResult>",
        allow_list: true,
        target: "<http://smartplatforms.org/terms#LabResult>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/LabResultStatus>"] = { 
    name: "LabResultStatus",
    uri: "<http://smartplatforms.org/terms/codes/LabResultStatus>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://www.w3.org/2000/01/rdf-schema#Literal>"] = { 
    name: "Literal",
    uri: "<http://www.w3.org/2000/01/rdf-schema#Literal>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#MedicalRecord>"] = { 
    name: "Medical Record",
    uri: "<http://smartplatforms.org/terms#MedicalRecord>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [ 
      {
        name: "hasStatement", 
        uri: "<http://smartplatforms.org/terms#hasStatement>",
        allow_list: true,
        target: "<http://smartplatforms.org/terms#Statement>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/MedicalRecordNumber>"] = { 
    name: "MedicalRecordNumber",
    uri: "<http://smartplatforms.org/terms/codes/MedicalRecordNumber>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Medication>"] = { 
    name: "Medication",
    uri: "<http://smartplatforms.org/terms#Medication>",
    is_statement: true,
    data_properties: [ 
      {
        name: "endDate", 
        uri: "<http://smartplatforms.org/terms#endDate>",
        allow_list: false
      },
      {
        name: "instructions", 
        uri: "<http://smartplatforms.org/terms#instructions>",
        allow_list: false
      },
      {
        name: "startDate", 
        uri: "<http://smartplatforms.org/terms#startDate>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "belongsTo", 
        uri: "<http://smartplatforms.org/terms#belongsTo>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#MedicalRecord>"
      },
      {
        name: "drugName", 
        uri: "<http://smartplatforms.org/terms#drugName>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      },
      {
        name: "frequency", 
        uri: "<http://smartplatforms.org/terms#frequency>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#ValueAndUnit>"
      },
      {
        name: "fulfillment", 
        uri: "<http://smartplatforms.org/terms#fulfillment>",
        allow_list: true,
        target: "<http://smartplatforms.org/terms#Fulfillment>"
      },
      {
        name: "provenance", 
        uri: "<http://smartplatforms.org/terms#provenance>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#Code>"
      },
      {
        name: "quantity", 
        uri: "<http://smartplatforms.org/terms#quantity>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#ValueAndUnit>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/MedicationProvenance>"] = { 
    name: "MedicationProvenance",
    uri: "<http://smartplatforms.org/terms/codes/MedicationProvenance>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/NDFRT>"] = { 
    name: "NDFRT",
    uri: "<http://smartplatforms.org/terms/codes/NDFRT>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://www.w3.org/2006/vcard/ns#Name>"] = { 
    name: "Name",
    uri: "<http://www.w3.org/2006/vcard/ns#Name>",
    is_statement: false,
    data_properties: [ 
      {
        name: "additional-name", 
        uri: "<http://www.w3.org/2006/vcard/ns#additional-name>",
        allow_list: true
      },
      {
        name: "family-name", 
        uri: "<http://www.w3.org/2006/vcard/ns#family-name>",
        allow_list: false
      },
      {
        name: "given-name", 
        uri: "<http://www.w3.org/2006/vcard/ns#given-name>",
        allow_list: false
      },
      {
        name: "honorific-prefix", 
        uri: "<http://www.w3.org/2006/vcard/ns#honorific-prefix>",
        allow_list: true
      },
      {
        name: "honorific-suffix", 
        uri: "<http://www.w3.org/2006/vcard/ns#honorific-suffix>",
        allow_list: true
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#NarrativeResult>"] = { 
    name: "NarrativeResult",
    uri: "<http://smartplatforms.org/terms#NarrativeResult>",
    is_statement: false,
    data_properties: [ 
      {
        name: "value", 
        uri: "<http://smartplatforms.org/terms#value>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#NominalResult>"] = { 
    name: "NominalResult",
    uri: "<http://smartplatforms.org/terms#NominalResult>",
    is_statement: false,
    data_properties: [ 
      {
        name: "value", 
        uri: "<http://smartplatforms.org/terms#value>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Ontology>"] = { 
    name: "Ontology",
    uri: "<http://smartplatforms.org/terms#Ontology>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#OrdinalResult>"] = { 
    name: "OrdinalResult",
    uri: "<http://smartplatforms.org/terms#OrdinalResult>",
    is_statement: false,
    data_properties: [ 
      {
        name: "value", 
        uri: "<http://smartplatforms.org/terms#value>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Organization>"] = { 
    name: "Organization",
    uri: "<http://smartplatforms.org/terms#Organization>",
    is_statement: false,
    data_properties: [ 
      {
        name: "organization-name", 
        uri: "<http://www.w3.org/2006/vcard/ns#organization-name>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "adr", 
        uri: "<http://www.w3.org/2006/vcard/ns#adr>",
        allow_list: false,
        target: "<http://www.w3.org/2006/vcard/ns#Address>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Panel>"] = { 
    name: "Panel",
    uri: "<http://smartplatforms.org/terms#Panel>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Participant>"] = { 
    name: "Participant",
    uri: "<http://smartplatforms.org/terms#Participant>",
    is_statement: false,
    data_properties: [ 
      {
        name: "role", 
        uri: "<http://smartplatforms.org/terms#role>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "organization", 
        uri: "<http://smartplatforms.org/terms#organization>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#Organization>"
      },
      {
        name: "person", 
        uri: "<http://smartplatforms.org/terms#person>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#Person>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Person>"] = { 
    name: "Person",
    uri: "<http://smartplatforms.org/terms#Person>",
    is_statement: false,
    data_properties: [ 
      {
        name: "bday", 
        uri: "<http://www.w3.org/2006/vcard/ns#bday>",
        allow_list: false
      },
      {
        name: "email", 
        uri: "<http://www.w3.org/2006/vcard/ns#email>",
        allow_list: false
      },
      {
        name: "ethnicity", 
        uri: "<http://smartplatforms.org/terms#ethnicity>",
        allow_list: false
      },
      {
        name: "gender", 
        uri: "<http://xmlns.com/foaf/0.1/gender>",
        allow_list: false
      },
      {
        name: "preferredLanguage", 
        uri: "<http://smartplatforms.org/terms#preferredLanguage>",
        allow_list: false
      },
      {
        name: "race", 
        uri: "<http://smartplatforms.org/terms#race>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "adr", 
        uri: "<http://www.w3.org/2006/vcard/ns#adr>",
        allow_list: true,
        target: "<http://www.w3.org/2006/vcard/ns#Address>"
      },
      {
        name: "n", 
        uri: "<http://www.w3.org/2006/vcard/ns#n>",
        allow_list: false,
        target: "<http://www.w3.org/2006/vcard/ns#Name>"
      },
      {
        name: "tel", 
        uri: "<http://www.w3.org/2006/vcard/ns#tel>",
        allow_list: true,
        target: "<http://www.w3.org/2006/vcard/ns#Tel>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Pharmacy>"] = { 
    name: "Pharmacy",
    uri: "<http://smartplatforms.org/terms#Pharmacy>",
    is_statement: false,
    data_properties: [ 
      {
        name: "ncpdpId", 
        uri: "<http://smartplatforms.org/terms#ncpdpId>",
        allow_list: false
      },
      {
        name: "organization-name", 
        uri: "<http://www.w3.org/2006/vcard/ns#organization-name>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "adr", 
        uri: "<http://www.w3.org/2006/vcard/ns#adr>",
        allow_list: false,
        target: "<http://www.w3.org/2006/vcard/ns#Address>"
      } 
    ]
  };


  type_definitions["<http://www.w3.org/2006/vcard/ns#Pref>"] = { 
    name: "Pref",
    uri: "<http://www.w3.org/2006/vcard/ns#Pref>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Problem>"] = { 
    name: "Problem",
    uri: "<http://smartplatforms.org/terms#Problem>",
    is_statement: true,
    data_properties: [ 
      {
        name: "endDate", 
        uri: "<http://smartplatforms.org/terms#endDate>",
        allow_list: false
      },
      {
        name: "notes", 
        uri: "<http://smartplatforms.org/terms#notes>",
        allow_list: false
      },
      {
        name: "startDate", 
        uri: "<http://smartplatforms.org/terms#startDate>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "belongsTo", 
        uri: "<http://smartplatforms.org/terms#belongsTo>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#MedicalRecord>"
      },
      {
        name: "problemName", 
        uri: "<http://smartplatforms.org/terms#problemName>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Provider>"] = { 
    name: "Provider",
    uri: "<http://smartplatforms.org/terms#Provider>",
    is_statement: false,
    data_properties: [ 
      {
        name: "bday", 
        uri: "<http://www.w3.org/2006/vcard/ns#bday>",
        allow_list: false
      },
      {
        name: "deaNumber", 
        uri: "<http://smartplatforms.org/terms#deaNumber>",
        allow_list: false
      },
      {
        name: "email", 
        uri: "<http://www.w3.org/2006/vcard/ns#email>",
        allow_list: false
      },
      {
        name: "ethnicity", 
        uri: "<http://smartplatforms.org/terms#ethnicity>",
        allow_list: false
      },
      {
        name: "gender", 
        uri: "<http://xmlns.com/foaf/0.1/gender>",
        allow_list: false
      },
      {
        name: "npiNumber", 
        uri: "<http://smartplatforms.org/terms#npiNumber>",
        allow_list: false
      },
      {
        name: "preferredLanguage", 
        uri: "<http://smartplatforms.org/terms#preferredLanguage>",
        allow_list: false
      },
      {
        name: "race", 
        uri: "<http://smartplatforms.org/terms#race>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "adr", 
        uri: "<http://www.w3.org/2006/vcard/ns#adr>",
        allow_list: true,
        target: "<http://www.w3.org/2006/vcard/ns#Address>"
      },
      {
        name: "n", 
        uri: "<http://www.w3.org/2006/vcard/ns#n>",
        allow_list: false,
        target: "<http://www.w3.org/2006/vcard/ns#Name>"
      },
      {
        name: "tel", 
        uri: "<http://www.w3.org/2006/vcard/ns#tel>",
        allow_list: true,
        target: "<http://www.w3.org/2006/vcard/ns#Tel>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#QuantitativeResult>"] = { 
    name: "QuantitativeResult",
    uri: "<http://smartplatforms.org/terms#QuantitativeResult>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [ 
      {
        name: "nonCriticalRange", 
        uri: "<http://smartplatforms.org/terms#nonCriticalRange>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#ValueRange>"
      },
      {
        name: "normalRange", 
        uri: "<http://smartplatforms.org/terms#normalRange>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#ValueRange>"
      },
      {
        name: "valueAndUnit", 
        uri: "<http://smartplatforms.org/terms#valueAndUnit>",
        allow_list: true,
        target: "<http://smartplatforms.org/terms#ValueAndUnit>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/RxNorm>"] = { 
    name: "RxNorm",
    uri: "<http://smartplatforms.org/terms/codes/RxNorm>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/RxNorm_Ingredient>"] = { 
    name: "RxNorm_Ingredient",
    uri: "<http://smartplatforms.org/terms/codes/RxNorm_Ingredient>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/RxNorm_Semantic>"] = { 
    name: "RxNorm_Semantic",
    uri: "<http://smartplatforms.org/terms/codes/RxNorm_Semantic>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#Statement>"] = { 
    name: "SMART Statement",
    uri: "<http://smartplatforms.org/terms#Statement>",
    is_statement: true,
    data_properties: [  
    ],
    object_properties: [ 
      {
        name: "belongsTo", 
        uri: "<http://smartplatforms.org/terms#belongsTo>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#MedicalRecord>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/SNOMED>"] = { 
    name: "SNOMED",
    uri: "<http://smartplatforms.org/terms/codes/SNOMED>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://www.w3.org/2006/vcard/ns#Tel>"] = { 
    name: "Tel",
    uri: "<http://www.w3.org/2006/vcard/ns#Tel>",
    is_statement: false,
    data_properties: [ 
      {
        name: "value", 
        uri: "<http://www.w3.org/1999/02/22-rdf-syntax-ns#value>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/TranslationFidelity>"] = { 
    name: "TranslationFidelity",
    uri: "<http://smartplatforms.org/terms/codes/TranslationFidelity>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/UNII>"] = { 
    name: "UNII",
    uri: "<http://smartplatforms.org/terms/codes/UNII>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#User>"] = { 
    name: "User",
    uri: "<http://smartplatforms.org/terms#User>",
    is_statement: false,
    data_properties: [ 
      {
        name: "bday", 
        uri: "<http://www.w3.org/2006/vcard/ns#bday>",
        allow_list: false
      },
      {
        name: "department", 
        uri: "<http://smartplatforms.org/terms#department>",
        allow_list: false
      },
      {
        name: "email", 
        uri: "<http://www.w3.org/2006/vcard/ns#email>",
        allow_list: false
      },
      {
        name: "ethnicity", 
        uri: "<http://smartplatforms.org/terms#ethnicity>",
        allow_list: false
      },
      {
        name: "gender", 
        uri: "<http://xmlns.com/foaf/0.1/gender>",
        allow_list: false
      },
      {
        name: "preferredLanguage", 
        uri: "<http://smartplatforms.org/terms#preferredLanguage>",
        allow_list: false
      },
      {
        name: "race", 
        uri: "<http://smartplatforms.org/terms#race>",
        allow_list: false
      },
      {
        name: "role", 
        uri: "<http://smartplatforms.org/terms#role>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "adr", 
        uri: "<http://www.w3.org/2006/vcard/ns#adr>",
        allow_list: true,
        target: "<http://www.w3.org/2006/vcard/ns#Address>"
      },
      {
        name: "n", 
        uri: "<http://www.w3.org/2006/vcard/ns#n>",
        allow_list: false,
        target: "<http://www.w3.org/2006/vcard/ns#Name>"
      },
      {
        name: "tel", 
        uri: "<http://www.w3.org/2006/vcard/ns#tel>",
        allow_list: true,
        target: "<http://www.w3.org/2006/vcard/ns#Tel>"
      } 
    ]
  };


  type_definitions["<http://www.w3.org/2006/vcard/ns#VCard>"] = { 
    name: "VCard",
    uri: "<http://www.w3.org/2006/vcard/ns#VCard>",
    is_statement: false,
    data_properties: [ 
      {
        name: "bday", 
        uri: "<http://www.w3.org/2006/vcard/ns#bday>",
        allow_list: false
      },
      {
        name: "email", 
        uri: "<http://www.w3.org/2006/vcard/ns#email>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "adr", 
        uri: "<http://www.w3.org/2006/vcard/ns#adr>",
        allow_list: true,
        target: "<http://www.w3.org/2006/vcard/ns#Address>"
      },
      {
        name: "n", 
        uri: "<http://www.w3.org/2006/vcard/ns#n>",
        allow_list: false,
        target: "<http://www.w3.org/2006/vcard/ns#Name>"
      },
      {
        name: "tel", 
        uri: "<http://www.w3.org/2006/vcard/ns#tel>",
        allow_list: true,
        target: "<http://www.w3.org/2006/vcard/ns#Tel>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#ValueAndUnit>"] = { 
    name: "ValueAndUnit",
    uri: "<http://smartplatforms.org/terms#ValueAndUnit>",
    is_statement: false,
    data_properties: [ 
      {
        name: "unit", 
        uri: "<http://smartplatforms.org/terms#unit>",
        allow_list: false
      },
      {
        name: "value", 
        uri: "<http://smartplatforms.org/terms#value>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#ValueRange>"] = { 
    name: "ValueRange",
    uri: "<http://smartplatforms.org/terms#ValueRange>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [ 
      {
        name: "maximum", 
        uri: "<http://smartplatforms.org/terms#maximum>",
        allow_list: true,
        target: "<http://smartplatforms.org/terms#ValueAndUnit>"
      },
      {
        name: "minimum", 
        uri: "<http://smartplatforms.org/terms#minimum>",
        allow_list: true,
        target: "<http://smartplatforms.org/terms#ValueAndUnit>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#ValueRatio>"] = { 
    name: "ValueRatio",
    uri: "<http://smartplatforms.org/terms#ValueRatio>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [ 
      {
        name: "denominator", 
        uri: "<http://smartplatforms.org/terms#denominator>",
        allow_list: true,
        target: "<http://smartplatforms.org/terms#ValueAndUnit>"
      },
      {
        name: "numerator", 
        uri: "<http://smartplatforms.org/terms#numerator>",
        allow_list: true,
        target: "<http://smartplatforms.org/terms#ValueAndUnit>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/codes/VitalSign>"] = { 
    name: "VitalSign",
    uri: "<http://smartplatforms.org/terms/codes/VitalSign>",
    is_statement: false,
    data_properties: [ 
      {
        name: "identifier", 
        uri: "<http://purl.org/dc/terms/identifier>",
        allow_list: false
      },
      {
        name: "system", 
        uri: "<http://smartplatforms.org/terms#system>",
        allow_list: false
      },
      {
        name: "title", 
        uri: "<http://purl.org/dc/terms/title>",
        allow_list: false
      } 
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#VitalSign>"] = { 
    name: "VitalSign",
    uri: "<http://smartplatforms.org/terms#VitalSign>",
    is_statement: false,
    data_properties: [ 
      {
        name: "unit", 
        uri: "<http://smartplatforms.org/terms#unit>",
        allow_list: false
      },
      {
        name: "value", 
        uri: "<http://smartplatforms.org/terms#value>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "vitalName", 
        uri: "<http://smartplatforms.org/terms#vitalName>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#CodedValue>"
      } 
    ]
  };


  type_definitions["<http://smartplatforms.org/terms#VitalSigns>"] = { 
    name: "VitalSigns",
    uri: "<http://smartplatforms.org/terms#VitalSigns>",
    is_statement: true,
    data_properties: [ 
      {
        name: "date", 
        uri: "<http://purl.org/dc/terms/date>",
        allow_list: false
      } 
    ],
    object_properties: [ 
      {
        name: "belongsTo", 
        uri: "<http://smartplatforms.org/terms#belongsTo>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#MedicalRecord>"
      },
      {
        name: "bloodPressure", 
        uri: "<http://smartplatforms.org/terms#bloodPressure>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#BloodPressure>"
      },
      {
        name: "bodyMassIndex", 
        uri: "<http://smartplatforms.org/terms#bodyMassIndex>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#VitalSign>"
      },
      {
        name: "encounter", 
        uri: "<http://smartplatforms.org/terms#encounter>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#Encounter>"
      },
      {
        name: "heartRate", 
        uri: "<http://smartplatforms.org/terms#heartRate>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#VitalSign>"
      },
      {
        name: "height", 
        uri: "<http://smartplatforms.org/terms#height>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#VitalSign>"
      },
      {
        name: "oxygenSaturation", 
        uri: "<http://smartplatforms.org/terms#oxygenSaturation>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#VitalSign>"
      },
      {
        name: "respiratoryRate", 
        uri: "<http://smartplatforms.org/terms#respiratoryRate>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#VitalSign>"
      },
      {
        name: "temperature", 
        uri: "<http://smartplatforms.org/terms#temperature>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#VitalSign>"
      },
      {
        name: "weight", 
        uri: "<http://smartplatforms.org/terms#weight>",
        allow_list: false,
        target: "<http://smartplatforms.org/terms#VitalSign>"
      } 
    ]
  };


  type_definitions["<http://www.w3.org/2006/vcard/ns#Work>"] = { 
    name: "Work",
    uri: "<http://www.w3.org/2006/vcard/ns#Work>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://www.w3.org/2001/XMLSchema#anyURI>"] = { 
    name: "anyURI",
    uri: "<http://www.w3.org/2001/XMLSchema#anyURI>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://smartplatforms.org/terms/api#call>"] = { 
    name: "call",
    uri: "<http://smartplatforms.org/terms/api#call>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [  
    ]
  };


  type_definitions["<http://www.w3.org/2001/XMLSchema#dateTime>"] = { 
    name: "dateTime",
    uri: "<http://www.w3.org/2001/XMLSchema#dateTime>",
    is_statement: false,
    data_properties: [  
    ],
    object_properties: [  
    ]
  };


})(window);

